# https://devrescue.com/python-rsa-encrypt-decrypt-example/
# https://m.youtube.com/watch?v=4zahvcJ9glg
# https://www.youtube.com/watch?v=oOcTVTpUsPQ
# https://brilliant.org/wiki/rsa-encryption/
#
clean: 
	@rm -rf __pycache__ 
simple:
	@python3 simple.py 

rsa:
	@python3 rsa.py 
